# Generated by Django 2.1 on 2019-05-15 12:47

# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Resource',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
#                 ('title', models.CharField(max_length=100)),
#                 ('description', models.TextField()),
#                 ('file', models.TextField()),
#                 ('tags', models.BooleanField(default=False)),
#                 ('createdAt', models.DateTimeField(auto_now_add=True)),
#                 ('updatedAt', models.DateTimeField(auto_now_add=True)),
#             ],
#         ),
#     ]